#!/bin/bash

SOURCE_FILE=java/FetchFml.java
CLASS_FILE=java/FetchFml.class

if [[ $# < 1 ]];
then
echo Usage: fetchfml-version {minecraft-version}
exit 1;
fi;

MINECRAFT_VERSION=$1

if [ ! -e $CLASS_FILE ];
then
javac $SOURCE_FILE;
fi;

if [ ! -e $CLASS_FILE ];
then
echo unable to compile $SOURCE_FILE;
exit 1;
fi;

FML_VERSION=$(java -cp java FetchFml $MINECRAFT_VERSION);

if [[ $? != 0 ]];
then
echo FetchFml.java errored
exit 1;
fi;

echo $FML_VERSION;